---

- name: Install required packages for SnapRAID installation
  ansible.builtin.apt:
    name:
      - build-essential
      - libz-dev
    state: present
    update_cache: true
  become: true

- name: Download SnapRAID tarball
  ansible.builtin.get_url:
    url: "{{ snapraid_package_url }}"
    dest: "/tmp/snapraid.tar.gz"
    mode: '0755'
  notify: Cleanup SnapRAID download

- name: Extract SnapRAID tarball
  ansible.builtin.unarchive:
    src: "/tmp/snapraid.tar.gz"
    dest: "/tmp/"
    remote_src: yes
  notify: Cleanup SnapRAID download

- name: Configure SnapRAID
  ansible.builtin.command:
    cmd: "./configure"
    chdir: "/tmp/snapraid-{{ snapraid_version_num }}"

- name: Compile SnapRAID
  ansible.builtin.command:
    cmd: "make"
    chdir: "/tmp/snapraid-{{ snapraid_version_num }}"

- name: Install SnapRAID
  ansible.builtin.command:
    cmd: "sudo make install"
    chdir: "/tmp/snapraid-{{ snapraid_version_num }}"
  become: true
