---

- name: docker compose | Remove old Docker Compose binary
  ansible.builtin.file:
    path: /usr/local/lib/docker/cli-plugins/docker-compose
    state: absent

- name: docker compose | Check if Docker Compose is installed
  ansible.builtin.command: docker compose version
  no_log: true
  register: compose_check
  ignore_errors: true
  changed_when: false

- name: docker compose | Install Docker Compose
  ansible.builtin.apt:
    name: docker-compose-plugin
    update_cache: true
    state: present
  when: compose_check.rc != 0
  ignore_errors: "{{ ansible_check_mode }}"

- name: docker compose | Update Docker Compose
  ansible.builtin.apt:
    name: docker-compose-plugin
    update_cache: true
    state: latest # noqa package-latest
  when:
    - compose_update
    - compose_check.rc == 0
  ignore_errors: "{{ ansible_check_mode }}"