---

- name: Check if btrfs-progs is installed
  ansible.builtin.command:
    cmd: btrfs --version
  register: installed_version
  changed_when: false
  ignore_errors: true

- name: Set update_needed to true if btrfs is not installed
  ansible.builtin.set_fact:
    update_needed: true
  when: installed_version.rc != 0

- name: Find latest release of mergerfs
  community.general.github_release:
    user: kdave
    repo: btrfs-progs
    action: latest_release
  register: btrfs_latest_release
  delegate_to: localhost
  run_once: true
  become: false

- name: Set latest btrfs-progs version fact
  ansible.builtin.set_fact:
    btrfs_latest_version: "{{ btrfs_latest_release.tag }}"

- name: Extract version number from installed version
  ansible.builtin.set_fact:
    installed_version_number: "{{ installed_version.stdout.split()[-1][1:] }}"

- name: Compare installed version with the latest version
  ansible.builtin.set_fact:
    update_needed: "{{ btrfs_latest_version != installed_version_number }}"

- name: debug installed_version_number
  debug:
    var: installed_version_number

- name: debug btrfs_latest_version
  debug:
    var: btrfs_latest_version

- name: Install/update btrfs
  ansible.builtin.include_tasks:
    file: install.yml
  when: update_needed
