---

- name: Ensure the backports list file exists
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/bookworm-backports.list
    state: touch
    owner: root
    group: root
    mode: '0644'

- name: Add Debian backports repository
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/bookworm-backports.list
    line: "{{ item }}"
    state: present
  loop:
    - "deb http://deb.debian.org/debian bookworm-backports main contrib"
    - "deb-src http://deb.debian.org/debian bookworm-backports main contrib"

- name: Set priority for ZFS packages from backports
  ansible.builtin.copy:
    dest: /etc/apt/preferences.d/90_zfs
    content: |
      Package: src:zfs-linux
      Pin: release n=bookworm-backports
      Pin-Priority: 990

- name: Install necessary packages for ZFS
  ansible.builtin.apt:
    name: "{{ item }}"
    state: latest
  loop:
    - dpkg-dev
    - linux-headers-generic
    - linux-image-generic
    - zfs-dkms
    - zfsutils-linux
