---
- name: Check if zfsutils-linux is installed
  ansible.builtin.shell: dpkg-query -W -f='${Status}' zfsutils-linux 2>/dev/null | grep -c "ok installed"
  register: zfs_installed
  changed_when: false
  ignore_errors: true

- name: Install zfsutils
  ansible.builtin.include_tasks:
    file: "{{ ansible_distribution | lower }}.yml"

- name: Load ZFS module
  ansible.builtin.command:
    cmd: modprobe zfs
    warn: no
  when: zfs_installed.stdout == "0"
