---

- name: Ensure universe repository is enabled
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list
    line: "deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }} main universe"
    state: present
  when: zfs_installed.stdout == "0"

- name: Install or Upgrade ZFS utilities
  ansible.builtin.apt:
    name: zfsutils-linux
    update_cache: true
    state: latest
