---

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  listen: systemd handler
  when: molecule_yml is not defined

- name: Start and enable Docker systemd services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - docker
    - containerd
  listen: systemd handler
  when: molecule_yml is not defined
