---
#openzfs
zfs_pools:
  - name: array01
    vdevs:
      - mirror
      - /dev/disk/by-id/XXX
      - /dev/disk/by-id/XXX
      - mirror
      - /dev/disk/by-id/XXX
      - /dev/disk/by-id/XXX
    encrypted: yes
    properties:
      compression: 'lz4'
      dedup: 'on'
      autotrim: 'on'
      mountpoint: '/mnt/array01'
      encryption: 'on'
      keylocation: 'prompt'
      keyformat: 'passphrase'
      encryptionroot: "array01"
    scrub_schedule: "0 0 * * 0"  # Every Sunday at midnight
    state: present

  - name: array02
    vdevs:
      - mirror
      - /dev/disk/by-id/XXX
      - /dev/disk/by-id/XXX
    properties:
      compression: 'lz4'
      dedup: 'off'
      autotrim: 'on'
      mountpoint: '/mnt/array02'
    scrub_schedule: "0 0 * * 0"  # Every Sunday at midnight
    state: present


