- name: Ensure base mount point exists
  ansible.builtin.file:
    path: "/mnt/btrfs-root"
    state: directory

- name: Ensure mount point directories exist
  ansible.builtin.file:
    path: "/mnt/btrfs-root/{{ item | basename }}"
    state: directory
  loop: "{{ data_disks }}"
  loop_control:
    label: "{{ item }}"

- name: Check if the filesystem is already mounted
  ansible.builtin.shell:
    cmd: "mount | grep /mnt/btrfs-root/{{ item | basename }}"
  register: mount_check
  loop: "{{ data_disks }}"
  loop_control:
    label: "{{ item }}"
  ignore_errors: yes
  changed_when: false

- name: Mount the main Btrfs filesystem partition
  ansible.posix.mount:
    path: "/mnt/btrfs-root/{{ item | basename }}"
    src: "{{ item }}-part1" # TODO: should this use the same -part1 if else 1 logic from prepare_disks?
    fstype: btrfs
    state: mounted
  loop: "{{ data_disks }}"
  loop_control:
    label: "{{ item }}"
  ignore_errors: yes
  changed_when: false
  when: mount_check.results | selectattr('rc', 'equalto', 1) | list | length > 0

- name: Check if data subvolume exists
  shell: "btrfs subvolume list /mnt/btrfs-root/{{ item | basename }} | grep data"
  loop: "{{ data_disks }}"
  register: subvolume_check
  ignore_errors: true

- name: Create Btrfs data subvolume using command
  command: "btrfs subvolume create /mnt/btrfs-root/{{ item.item | basename }}/data"
  loop: "{{ subvolume_check.results }}"
  when: "'data' not in item.stdout"
  loop_control:
    label: "{{ item }}"
  ignore_errors: yes

- name: Unmount the fs
  ansible.posix.mount:
    path: /mnt/btrfs-root/{{ item | basename }}
    state: unmounted
  loop: "{{ data_disks }}"
  loop_control:
    label: "{{ item }}"

- name: Remove individual mount points
  ansible.builtin.file:
    path: "/mnt/btrfs-root/{{ item | basename }}"
    state: absent
  loop: "{{ data_disks }}"
  loop_control:
    label: "{{ item }}"
