---
- name: Reload systemd
  command: systemctl daemon-reload
  become: yes

- name: Restart mergerfs media cold
  systemd:
    name: mergerfs-media-cold
    state: restarted
    daemon_reload: yes
  become: yes

- name: Restart mergerfs media cache
  systemd:
    name: mergerfs-media-cache
    state: restarted
    daemon_reload: yes
  become: yes
