---

- name: Get user list
  ansible.builtin.getent:
    database: passwd

- name: Replace All Keys
  ansible.posix.authorized_key:
    user: "{{ item }}"
    state: present
    exclusive: true
    key: https://github.com/monstermuffin.keys
  loop:
    - monstermuffin
    - muffn
    - muffin
  when: item in getent_passwd | dict2items | map(attribute='key') | list
  register: user_exists
  changed_when: false
